#!/usr/bin/env python3
"""Generate a portable XeLaTeX header for Chinese/math Pandoc rendering."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from probe_pdf_render_env import find_project_resource_bundles


FANDOL_FILES = {
    "song": "FandolSong-Regular.otf",
    "hei": "FandolHei-Regular.otf",
    "kai": "FandolKai-Regular.otf",
}

TEX_GYRE_TERMES_FILES = {
    "regular": "texgyretermes-regular.otf",
    "bold": "texgyretermes-bold.otf",
    "italic": "texgyretermes-italic.otf",
    "bold_italic": "texgyretermes-bolditalic.otf",
}

TEX_GYRE_CURSOR_FILES = {
    "regular": "texgyrecursor-regular.otf",
    "bold": "texgyrecursor-bold.otf",
    "italic": "texgyrecursor-italic.otf",
    "bold_italic": "texgyrecursor-bolditalic.otf",
}


def find_file(root: Path, filename: str) -> Path | None:
    matches = list(root.rglob(filename))
    return matches[0] if matches else None


def kpsewhich_file(filename: str) -> Path | None:
    try:
        proc = subprocess.run(
            ["kpsewhich", filename],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    path = Path(proc.stdout.strip()) if proc.returncode == 0 and proc.stdout.strip() else None
    return path if path and path.exists() else None


def fontspec_file_block(command: str, files: dict[str, str]) -> str | None:
    regular = kpsewhich_file(files["regular"])
    if not regular:
        return None
    font_dir = regular.parent
    options = [f"Path={{{font_dir.as_posix()}/}}"]
    for key, option in [
        ("bold", "BoldFont"),
        ("italic", "ItalicFont"),
        ("bold_italic", "BoldItalicFont"),
    ]:
        filename = files.get(key)
        if filename and kpsewhich_file(filename):
            options.append(f"{option}={{{filename}}}")
    return "\\" + command + "[\n  " + ",\n  ".join(options) + f"\n]{{{files['regular']}}}"


def resource_font_block(resource_dir: Path | None) -> str | None:
    if not resource_dir:
        return None
    files = {key: find_file(resource_dir, name) for key, name in FANDOL_FILES.items()}
    if not files["song"]:
        return None
    font_dir = files["song"].parent
    options = [f"Path={{{font_dir.as_posix()}/}}"]
    if files["hei"] and files["hei"].parent == font_dir:
        options.append(f"BoldFont={{{FANDOL_FILES['hei']}}}")
    if files["kai"] and files["kai"].parent == font_dir:
        options.append(f"ItalicFont={{{FANDOL_FILES['kai']}}}")
    return "\\setCJKmainfont[\n  " + ",\n  ".join(options) + f"\n]{{{FANDOL_FILES['song']}}}"


def named_font_block(cjk_font: str) -> str:
    fallback_fonts = []
    for font in [
        cjk_font,
        "Noto Serif CJK SC",
        "Source Han Serif SC",
        "FandolSong",
        "AR PL UMing CN",
    ]:
        if font not in fallback_fonts:
            fallback_fonts.append(font)
    block = ""
    for font in reversed(fallback_fonts):
        if not block:
            block = f"\\setCJKmainfont{{{font}}}"
        else:
            block = f"\\IfFontExistsTF{{{font}}}{{\\setCJKmainfont{{{font}}}}}{{{block}}}"
    return block


def choose_resource_dir(root: Path, explicit: Path | None) -> Path | None:
    if explicit:
        return explicit.resolve()
    bundles = find_project_resource_bundles(root)
    usable = [Path(item["path"]) for item in bundles if item["usable_chinese_math_bundle"]]
    return usable[0] if usable else None


def latin_font_blocks(args: argparse.Namespace) -> str:
    main_block = fontspec_file_block("setmainfont", TEX_GYRE_TERMES_FILES)
    mono_block = fontspec_file_block("setmonofont", TEX_GYRE_CURSOR_FILES)
    if not main_block:
        main_block = f"\\IfFontExistsTF{{{args.main_font}}}{{\\setmainfont{{{args.main_font}}}}}{{}}"
    if not mono_block:
        mono_block = f"\\IfFontExistsTF{{{args.mono_font}}}{{\\setmonofont{{{args.mono_font}}}}}{{}}"
    return f"{main_block}\n{mono_block}"


def build_header(args: argparse.Namespace) -> str:
    root = args.root.resolve() if args.root else Path.cwd()
    resource_dir = choose_resource_dir(root, args.resource_dir)
    cjk_block = resource_font_block(resource_dir) or named_font_block(args.cjk_font)
    latin_block = latin_font_blocks(args)
    return f"""% Generated by build_chinese_math_header.py.
% Use with Pandoc --pdf-engine=xelatex for CJK/math documents.
\\usepackage{{fontspec}}
\\usepackage{{xeCJK}}
\\usepackage{{amsmath,amssymb}}
\\usepackage{{booktabs,longtable,array}}
\\usepackage{{graphicx}}
\\usepackage{{hyperref}}
\\hypersetup{{colorlinks=true,linkcolor=blue,urlcolor=blue,citecolor=blue}}
\\XeTeXlinebreaklocale "zh"
\\XeTeXlinebreakskip = 0pt plus 1pt
{latin_block}
{cjk_block}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, help="Header path. Defaults to stdout.")
    parser.add_argument(
        "--resource-dir",
        type=Path,
        help="Optional project-local resource directory containing TeX/fonts.",
    )
    parser.add_argument("--root", type=Path, help="Project root used to locate render resources.")
    parser.add_argument("--main-font", default="TeX Gyre Termes")
    parser.add_argument("--mono-font", default="TeX Gyre Cursor")
    parser.add_argument("--cjk-font", default="Noto Serif CJK SC")
    args = parser.parse_args()

    header = build_header(args)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(header, encoding="utf-8")
    else:
        print(header, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
