#!/usr/bin/env python3
"""Generate a portable XeLaTeX header for Chinese/math Pandoc rendering."""

from __future__ import annotations

import argparse
from pathlib import Path


FANDOL_FILES = {
    "song": "FandolSong-Regular.otf",
    "hei": "FandolHei-Regular.otf",
    "kai": "FandolKai-Regular.otf",
}


def find_file(root: Path, filename: str) -> Path | None:
    matches = list(root.rglob(filename))
    return matches[0] if matches else None


def resource_font_block(resource_dir: Path | None) -> str | None:
    if not resource_dir:
        return None
    files = {key: find_file(resource_dir, name) for key, name in FANDOL_FILES.items()}
    if not files["song"]:
        return None
    font_dir = files["song"].parent
    options = [f"Path={{{font_dir.as_posix()}/}}"]
    if files["hei"] and files["hei"].parent == font_dir:
        options.append(f"BoldFont={{{FANDOL_FILES['hei']}}}")
    if files["kai"] and files["kai"].parent == font_dir:
        options.append(f"ItalicFont={{{FANDOL_FILES['kai']}}}")
    return "\\setCJKmainfont[\n  " + ",\n  ".join(options) + f"\n]{{{FANDOL_FILES['song']}}}"


def named_font_block(cjk_font: str) -> str:
    fallback_fonts = []
    for font in [
        cjk_font,
        "Noto Serif CJK SC",
        "Source Han Serif SC",
        "FandolSong",
        "AR PL UMing CN",
    ]:
        if font not in fallback_fonts:
            fallback_fonts.append(font)
    block = ""
    for font in reversed(fallback_fonts):
        if not block:
            block = f"\\setCJKmainfont{{{font}}}"
        else:
            block = f"\\IfFontExistsTF{{{font}}}{{\\setCJKmainfont{{{font}}}}}{{{block}}}"
    return block


def build_header(args: argparse.Namespace) -> str:
    resource_dir = args.resource_dir.resolve() if args.resource_dir else None
    cjk_block = resource_font_block(resource_dir) or named_font_block(args.cjk_font)
    return f"""% Generated by build_chinese_math_header.py.
% Use with Pandoc --pdf-engine=xelatex for CJK/math documents.
\\usepackage{{fontspec}}
\\usepackage{{xeCJK}}
\\usepackage{{amsmath,amssymb}}
\\usepackage{{booktabs,longtable,array}}
\\usepackage{{graphicx}}
\\usepackage{{hyperref}}
\\hypersetup{{colorlinks=true,linkcolor=blue,urlcolor=blue,citecolor=blue}}
\\XeTeXlinebreaklocale "zh"
\\XeTeXlinebreakskip = 0pt plus 1pt
\\IfFontExistsTF{{{args.main_font}}}{{\\setmainfont{{{args.main_font}}}}}{{}}
\\IfFontExistsTF{{{args.mono_font}}}{{\\setmonofont{{{args.mono_font}}}}}{{}}
{cjk_block}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, help="Header path. Defaults to stdout.")
    parser.add_argument(
        "--resource-dir",
        type=Path,
        help="Optional project-local resource directory containing TeX/fonts.",
    )
    parser.add_argument("--main-font", default="TeX Gyre Termes")
    parser.add_argument("--mono-font", default="TeX Gyre Cursor")
    parser.add_argument("--cjk-font", default="Noto Serif CJK SC")
    args = parser.parse_args()

    header = build_header(args)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(header, encoding="utf-8")
    else:
        print(header, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
