#!/usr/bin/env python3
"""Audit active skill/plugin runtime text for brittle routing and unsafe legacy rules."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
SKILL_ROOTS = [ROOT / "skills", ROOT / "plugins" / "codex" / "plugins"]
DESCRIPTION_BANNED = ["PaperSpine", "ARS", "MoSAIC", "Nano Banana", "Claude"]
BODY_BANNED = [
    "notify_user",
    "npx skills add",
    "git pull",
    "git fetch origin",
    "For new documents: Scientific schematics should be generated by default",
    "Every hypothesis generation report MUST include",
    "This is not optional",
    "Generate ALL major visual elements using AI",
    "60-70% of poster area should be AI-generated visuals",
    "Use \"Claude\" as the author",
    "w:author=\"Claude\"",
    "next Claude",
    "user ALREADY said",
]
UNCONDITIONAL_VISUAL_PATTERNS = [
    re.compile(r"(?i)\b(always|must|mandatory|required)\b.{0,80}\b(ai-generated|generate(d)? (figures?|images?|schematics?|visuals?))"),
    re.compile(r"(?i)\b(every|all)\b.{0,60}\b(document|report|hypothesis|poster|chapter|section)s?\b.{0,80}\b(must|should|required)\b.{0,60}\b(figures?|images?|schematics?|visuals?|Mermaid)"),
]
ALLOW_BODY_PATH_PARTS = {"skills/tools/documents-media/perplexity-search/SKILL.md"}
FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.S)

def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))

def is_archived(text: str) -> bool:
    match = FRONTMATTER_RE.match(text)
    return bool(match and re.search(r"^status:\s*archived\s*$", match.group(1), re.M))

def get_frontmatter(text: str) -> str:
    match = FRONTMATTER_RE.match(text)
    return match.group(1) if match else ""

def get_description(frontmatter: str) -> str:
    match = re.search(r"^description:\s*(.*)$", frontmatter, re.M)
    return match.group(1) if match else ""

def iter_runtime_files() -> Iterable[Path]:
    for root in SKILL_ROOTS:
        if not root.exists():
            continue
        yield from root.rglob("SKILL.md")
        yield from root.rglob("source.md")

def audit() -> list[str]:
    errors: list[str] = []
    for path in sorted(set(iter_runtime_files())):
        text = path.read_text(errors="replace")
        r = rel(path)
        if is_archived(text):
            continue
        frontmatter = get_frontmatter(text)
        description = get_description(frontmatter)
        for bad in DESCRIPTION_BANNED:
            if bad in description:
                errors.append(f"{r}: description contains brittle route/provider term: {bad}")
        body_allow = r in ALLOW_BODY_PATH_PARTS or "/perplexity-search/" in r
        if body_allow:
            continue
        for bad in BODY_BANNED:
            if bad in text:
                errors.append(f"{r}: contains banned runtime phrase: {bad}")
        for pattern in UNCONDITIONAL_VISUAL_PATTERNS:
            for match in pattern.finditer(text):
                line = text.count("\n", 0, match.start()) + 1
                snippet = " ".join(match.group(0).split())[:180]
                errors.append(f"{r}:{line}: possible unconditional visual rule: {snippet}")
    return errors

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if issues are found")
    parser.add_argument("--json", action="store_true", help="print machine-readable results")
    args = parser.parse_args()
    errors = audit()
    if args.json:
        print(json.dumps({"errors": errors}, ensure_ascii=False, indent=2))
    elif errors:
        print("Runtime text audit found issues:")
        for e in errors:
            print(f"- {e}")
    else:
        print("Runtime text audit passed.")
    return 1 if errors and args.check else 0

if __name__ == "__main__":
    raise SystemExit(main())
